/*
CREATE TABLE PLANO(
	NUMERO CHAR(2) NOT NULL,
    DESCRICAO VARCHAR (30),
    VALOR decimal (10,2),
    CONSTRAINT pk_PLANO primary key (NUMERO)
);


CREATE TABLE ASSOCIADO (
	PLANO CHAR(2) NOT NULL,
    NOME VARCHAR (30),
    ENDERECO VARCHAR(35),
    CIDADE VARCHAR(20),
    ESTADO CHAR(2),
    CEP VARCHAR(9),
    CONSTRAINT pk_ASSOCIADO primary key (NOME)
);


INSERT INTO PLANO 
    (NUMERO, DESCRICAO,VALOR) 
VALUES
('S1','Simples1','200.00'),
	('S2','Simples2','150.00'),
    ('S3','Simples3','100.00'),
	('P1','Plus1','350.00'),
    ('P2','Plus2','300.00'),
	('P3','Plus3','250.00'),
    ('V1','Vip1','500.00'),
	('V2','Vip2','450.00'),
    ('V3','Vip3','400.00');


INSERT INTO ASSOCIADO 
    (PLANO,NOME,ENDERECO,CIDADE,ESTADO,CEP) 
VALUES
('S1','JOS� ANTONIO DA SILVA','R. FELIPE DO AMARAL. 3450','FAZENDA RIO GRANDE','PR','83830-000'),
('S1','MARIA DA SILVA SOBRINHO','R. FELIPE DE JESUS, 1245','ARAUCARIA','PR','83702-170'),
('S1','PEDRO JOSE DE OLIVEIRA','R. AGRIPINO DIAS. 155','FAZENDA RIO GRANDE','PR','83830-011'),
('S2','ANTONIA DE FERNANDES','R. PE. EZEQUIEL, 567','ARAUCARIA','PR','83702-175'),
('S2','ANTONIO DO PRADO','R. INDIO TABAJARA, 55','PIRAQUARA','PR','83310-999'),
('S3','WILSON DE SENA','R. ARAPIRACA. 1234','CAMPO LARGO','PR','83601-001'),
('S3','SILVIA DE ABREU','R. DR. JOAO DA SILVA, 5','PONTA GROSSA','PR','84010-112'),
('P1','ODEIE DA CONCEI��O','R. VOLUNT�RIOS DA PATRIA. 10','CURITIBA','PR','80060-550'),
('P2','JOAO CARLOS MACEDO','R. VISTA ALEGRE. 500','CURITIBA','PR','80430-990'),
('P3','CONCEI��O DA SILVA','AV. VITORIO DO AMPARO. 11','RIO BRANCO DO SUL','PR','83540-988'),
('P3','PAULO BRUNO AMARAL','R. ARCENZIO BRILHANTE. 88','S�O JOS� DOS PINHAIS','PR','83040-999'),
('P3','WALDENICE DE OLIVEIRA','R. OURO VELHO, 12','S�O JOS� DOS PINHAIS','PR','83040-998'),
('P3','MARCOS DO AMARAL','R. DO OUVIDOR. 67','PIRAQUARA','PR','83310-555'),
('V1','MURILO DE SANTANA','R. PRATA DA CASA 245','S�O JOS� DOS PINHAIS','PR','83075-111'),
('V1','LUIZA ONOFRE FREITAS','R. VICENTE DE ABREU. 55','PONTA GROSSA','PR','84010-667'),
('V2','MELISSA DE ALMEIDA','R. FERNANDO ANTONIO.2345','CURITIBA','PR','80410-987'),
('V2','JOAO INACIO DA CONCEICAO','R. PENELOPE CHARMOSA 34','PARANAGU�','PR','83203-888'),
('S3','AUGUSTA DE ABREU','AV. RIO DA SERRA, 909','PONTA GROSSA','PR','84010-333'),
('V3','ILDA DE MELO DA CUNHA','AV. POR DO SOL 546','PONTA GROSSA','PR','84010-144'),
('V3','MARCOS DA CUNHA','AV. PEDROSO DE MORAES 12','CURITIBA','PR','80420-144');
*/
/*
select ASSOCIADO.NOME, ASSOCIADO.PLANO, PLANO.VALOR 
from ASSOCIADO inner join PLANO 
on ASSOCIADO.PLANO = PLANO.NUMERO 
where ASSOCIADO.CIDADE = 'S�O JOS� DOS PINHAIS' and ASSOCIADO.PLANO = 'V1';
*/
/*3)
select ASSOCIADO.NOME, ASSOCIADO.PLANO, PLANO.VALOR 
from ASSOCIADO inner join PLANO 
on ASSOCIADO.PLANO = PLANO.NUMERO;
*/
/*
select NUMERO as plano, avg(VALOR) as media_pago from PLANO group by NUMERO;
*/
/*
select NOME, PLANO from ASSOCIADO;
*/
/*
select NOME,CIDADE from ASSOCIADO where CIDADE = 'FAZENDA RIO GRANDE' or CIDADE = 'ARAUCARIA' order by CIDADE;
*/
/*
select ASSOCIADO.NOME, ASSOCIADO.PLANO, PLANO.VALOR from ASSOCIADO
inner join PLANO on ASSOCIADO.PLANO = PLANO.NUMERO
where  PLANO.NUMERO = 'V2' and CIDADE = 'CURITIBA' or PLANO.NUMERO ='V3' and CIDADE = 'CURITIBA'
order by ASSOCIADO.NOME;
*/
/*
select NUMERO from PLANO where VALOR between 300.00 and 500.00
*/
/*
select count(NOME) as quantidade_S1 from ASSOCIADO where PLANO = 'S1';
*/
/*
select ASSOCIADO.PLANO,ASSOCIADO.NOME,ASSOCIADO.ENDERECO,ASSOCIADO.CIDADE,ASSOCIADO.ESTADO,ASSOCIADO.CEP,PLANO.NUMERO,PLANO.DESCRICAO,PLANO.VALOR,PLANO from ASSOCIADO 
inner join PLANO on ASSOCIADO.PLANO = PLANO.NUMERO where ASSOCIADO.NOME like '%SILVA%';
*/
/*
update Produto set Valor_Unit = (1.025*Valor_Unit) where Valor_Unit < (select avg(Valor_Unit) from Produto);
*/
/*
update PlANO set VALOR = (1.03 * VALOR) where NUMERO = 'V1' or NUMERO = 'V2' or NUMERO = 'V3';
*/
/*
select VALOR from PLANO where NUMERO like 'V%';
*/