nome = input('Digite seu nome completo: ')
print('Analisando seu nome....')
print('Seu nome em maiusculas é {}'.format(nome.upper()))
print('Seu nome em minuscula é {}'.format(nome.lower()))
print('Seu nome tem {} caracteres'.format(len(nome) -nome.count('')))
#print('Seu primeiro nome é {} e ele tem {}'.format(nome.split(0)),len(nome))